### ISSUE TITLE
Wrong connector used on board

### ISSUE THREAD

**Issue by VinnyCordeiro** [jyancat/RS232-DB9-Expansion-Card#1]
Concerning the DE-9 connector for RS-232 usage the pinout on the schematics is correct, but it was used a receptacle connector, which is wrong: it should have been used the plug connector (the one that have visible pins on it). To reflect that the chosen 3d model should also be changed, fortunately the chosen manufacturer have a correspondent version that have the same footprint, not requiring changes on the PCB. The model name is different though, and should be changed to reflect that.

However, if the intention is to really use the chosen connector, then the pinout should be mirrored.

* Information about pinout: https://pinoutguide.com/SerialPortsCables/9to25Serial_pinout.shtml
* Manufacturer page to obtain 3d model file: https://cloud.kycon.com/website/ajaxps1.html?pno=K31X (the correct model is K31X-E9P-NJ)

**Comment by jyancat** [comment]
I have already swapped the connector over to the suggested part, this was an oversight on my part and all new stock uses the correctly gendered connector.

**Comment by jyancat** [comment]
I've just updated the repo with updated PCB design files with the correct gendered connector.
